name: Release

on:
  push:
    tags:
      - "v[0-9]*"

jobs:
  ci:
    name: Run CI workflow
    uses: ./.github/workflows/ci.yml

  release:
    name: Create release
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run build script
        run: |
          scripts/build.sh ${{ github.ref_name }}
          printf '%s\n' build/dist/* | head -n1 | sed 's/^/phar_path=/' >>"$GITHUB_ENV"

      # Requires Actions > General > Workflow permissions > Read and write permissions
      - name: Create release
        run: |
          gh release create ${{ github.ref_name }} ${{ env.phar_path }} --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
